batch_size: 128
epochs: 30
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

# Evaluation
model_path: /content/drive/MyDrive/DL/最終課題/dl_lecture_competition_pub-MEG-competition/outputs/2024-07-17/04-11-02/model_best.pt